test "clone citizen":
    spawn citizen named "Original" at spawn of world "world"
    set {npc::1} to last created citizen
    clone npc {npc::1} at spawn of world "world"
    assert true is true with "was wrong"
    delete all npcs

test "clone citizen with new name":
    spawn citizen named "Original" at spawn of world "world"
    set {npc::1} to last created citizen
    clone npc {npc::1} at spawn of world "world" with new name "Clone"
    assert true is true with "was wrong"
    delete all npcs
