test "change citizen skin by url":
    spawn citizen named "test" at spawn of world "world"
    set {_npc} to last spawned npc
    change skin of {_npc} to url "https://www.minecraftskins.com/uploads/skins/2025/06/24/incognitoddm-23356583.png?v856"
    assert skin of {_npc} is skin from url "https://www.minecraftskins.com/uploads/skins/2025/06/24/incognitoddm-23356583.png?v856" with "was wrong"
    assert skin of {_npc} is skin from url "https://www.minecraftskins.com/uploads/skins/2025/06/20/glass-duck-23349737.png?v856" to fail with "was wrong"
    delete all citizens