test "change citizen skin by url":
    spawn citizen named "test" at spawn of world "world"
    set {_npc} to last spawned npc
    change skin of npc {_npc} to url "https://www.minecraftskins.com/uploads/skins/2025/08/09/technoblade-23459060.png?v921"
    assert value of npc skin of {_npc} is value of skin from url "https://www.minecraftskins.com/uploads/skins/2025/08/09/technoblade-23459060.png?v921" with "was wrong"
    assert value of npc skin of {_npc} is value of skin from url "https://www.minecraftskins.com/uploads/skins/2025/10/07/squid-game---square-23568183.png?v936" to fail with "was wrong"
    delete all citizens