test "change citizen skin from skin":
    spawn citizen named "test1" at spawn of world "world"
    set {_npc} to last created citizen

    change skin of {_npc} to skin from url "https://textures.minecraft.net/texture/e4af165698f313809f5e01bdf8863bc19e94aa8b863b936f8d33b59cdc9c57fb"
    assert npc skin of {_npc} is skin from url "https://textures.minecraft.net/texture/e4af165698f313809f5e01bdf8863bc19e94aa8b863b936f8d33b59cdc9c57fb" with "skin was not changed"
    change skin of {_npc} to skin from url "https://textures.minecraft.net/texture/2ff6d970b1b6243fe5a44c5ac540c320506987a5c55ba99a90f758b00d3e05a1"
    assert npc skin of {_npc} is skin from url "https://textures.minecraft.net/texture/2ff6d970b1b6243fe5a44c5ac540c320506987a5c55ba99a90f758b00d3e05a1" with "skin was not changed"