test "make citizen aggressive":
    spawn citizen named "test" at spawn of world "world"
    set {_npc} to last spawned npc
    make {_npc} aggressive
    assert npc {_npc} is aggressive with "was wrong"
    assert npc {_npc} is not aggressive to fail with "was wrong"
    make {_npc} passive
    assert npc {_npc} is not aggressive with "was wrong"
    assert npc {_npc} is aggressive to fail with "was wrong"
    delete all citizens