test "make citizen pathfind":
    spawn citizen named "test1" at spawn of world "world"
    set {_npc::1} to last spawned citizen
    set {_loc::1} to location 100 blocks north of {_npc::1}
    make npc {_npc::1} pathfind to {_loc::1}
    assert npc {_npc::1} is navigating with "was wrong (isNavigating)"
    assert npc {_npc::1} is navigating to {_loc::1} with "was wrong (IsNavigatingTo)"
    spawn citizen named "test2" at spawn of world "world"
    set {_npc::2} to last spawned citizen
    set {_loc::2} to location 100 blocks south of {_npc::2}
    make npc {_npc::2} pathfind to {_loc::2}
    make npc {_npc::1} pathfind to {_loc::1}

    assert npc {_npc::2} is navigating to {_loc::2} with "was wrong (isNavigating1)"
    assert npc {_npc::1} is navigating to {_loc::1} with "was wrong (isNavigating2)"
    assert npc {_npc::1} and {_npc::2} are navigating with "was wrong (areNavigating1)"

    pause {_npc::1}
    assert npc {_npc::1} are not navigating with "was wrong (areNavigating2)"
    pause {_npc::2}
    assert npc {_npc::1} and {_npc::2} are not navigating with "was wrong (areNotNavigating)"
    delete all citizens