test "make citizen targetable":
    spawn citizen named "test1" at spawn of world "world"
    set {_npc::1} to last spawned citizen
    make npc {_npc::1} targetable
    assert {_npc::1} is targetable with "was wrong"
    spawn citizen named "test2" at spawn of world "world"
    set {_npc::2} to last spawned citizen
    make npc {_npc::2} targetable
    assert {_npc::1} and {_npc::2} are targetable with "was wrong"
    make npc {_npc::1} not targetable
    assert {_npc::1} and {_npc::2} are targetable to fail with "was wrong"
    assert {_npc::1} and {_npc::2} aren't targetable to fail with "was wrong"
    make npc {_npc::2} not targetable
    assert {_npc::1} and {_npc::2} are not targetable with "was wrong"
    delete all citizens