test "make citizen flyable":
    spawn citizen named "test" at spawn of world "world"
    set {_npc} to last spawned npc
    make {_npc} flyable
    assert npc {_npc} is flyable with "was wrong"
    assert npc {_npc} is not flyable to fail with "was wrong"
    make {_npc} unflyable
    assert npc {_npc} is not flyable with "was wrong"
    assert npc {_npc} is flyable to fail with "was wrong"
    delete all citizens