test "make citizen glow":
    spawn citizen named "test" at spawn of world "world"
    set {_npc} to last spawned npc
    make npc {_npc} start glowing
    assert npc {_npc} is glowing with "was wrong"
    assert npc {_npc} is not glowing to fail with "was wrong"
    make npc {_npc} stop glowing
    assert npc {_npc} is not glowing with "was wrong"
    assert npc {_npc} is glowing to fail with "was wrong"
    delete all npcs


test "make citizen glow with color":
    spawn citizen named "test" at spawn of world "world"
    set {_npc} to last spawned npc
    make npc {_npc} start glowing with colour red
    assert npc {_npc} is glowing with "was wrong"
    assert npc {_npc} is not glowing to fail with "was wrong"
    delete all npcs