test "change citizen skin":
    spawn citizen named "test" at spawn of world "world"
    set {_npc} to last spawned npc
    change skin of npc {_npc} to skin from url "https://www.minecraftskins.com/uploads/skins/2025/08/09/technoblade-23459060.png?v921"
    broadcast npc skin of {_npc}
    broadcast value of npc skin of {_npc}
    assert value of npc skin of {_npc} is value of skin from url "https://www.minecraftskins.com/uploads/skins/2025/08/09/technoblade-23459060.png?v921" with "was wrong"
    assert value of npc skin of {_npc} is value of skin from url "https://www.minecraftskins.com/uploads/skins/2025/07/31/duck-became-sans-23438694.png?v896" to fail with "was wrong"
    delete all citizens