test "citizen is vulnerable":
    spawn citizen named "test1" at spawn of world "world"
    set {_npc::1} to last spawned citizen
    make {_npc::1} vulnerable
    assert {_npc::1} is vulnerable with "was wrong"
    spawn citizen named "test2" at spawn of world "world"
    set {_npc::2} to last spawned citizen
    make {_npc::2} unprotected
    assert {_npc::1} and {_npc::2} are vulnerable with "was wrong"
    make {_npc::1} invulnerable
    assert {_npc::1} and {_npc::2} are vulnerable to fail with "was wrong"
    assert {_npc::1} and {_npc::2} are protected to fail with "was wrong"
    make {_npc::2} protected
    assert {_npc::1} and {_npc::2} are protected with "was wrong"
    delete all citizens