test "citizen is paused":
    spawn citizen named "test1" at spawn of world "world"
    set {_npc::1} to last spawned citizen
    pause {_npc::1}
    assert {_npc::1} is paused with "was wrong"
    spawn citizen named "test2" at spawn of world "world"
    set {_npc::2} to last spawned citizen
    pause {_npc::2}
    assert {_npc::1} and {_npc::2} are paused with "was wrong"
    make npc {_npc::1} pathfind to the location (100, 100, 100) in world "world"
    assert {_npc::1} and {_npc::2} are paused to fail with "was wrong"
    assert {_npc::1} and {_npc::2} aren't paused to fail with "was wrong"
    make npc {_npc::1} pathfind to the location (100, 100, 100) in world "world"
    assert {_npc::1} and {_npc::2} are not paused with "was wrong"
    delete all citizens