test "citizen is aggressive":
    spawn citizen named "test1" at location (0,0,0)
    set {_npc::1} to last spawned citizen
    make {_npc::1} aggressive
    assert {_npc::1} is aggressive with "was wrong"
    spawn citizen named "test2" at location (1,1,1)
    set {_npc::2} to last spawned citizen
    make {_npc::2} aggressive
    assert {_npc::1} and {_npc::2} are aggressive with "was wrong"
    make {_npc::1} passive
    assert {_npc::1} and {_npc::2} are aggressive with "was wrong"
    assert {_npc::1} and {_npc::2} aren't aggressive with "was wrong"
    make {_npc::2} passive
    assert {_npc::1} and {_npc::2} are not aggressive with "was wrong"