test "citizen is flyable":
    spawn citizen named "test1" at spawn of world "world"
    set {_npc::1} to last spawned citizen
    make {_npc::1} flyable
    assert npc {_npc::1} is flyable with "was wrong"
    spawn citizen named "test2" at spawn of world "world"
    set {_npc::2} to last spawned citizen
    make {_npc::2} flyable
    assert npc {_npc::1} and {_npc::2} are flyable with "was wrong"
    make {_npc::1} not flyable
    assert npc {_npc::1} and {_npc::2} are flyable to fail with "was wrong"
    assert npc {_npc::1} and {_npc::2} aren't flyable to fail with "was wrong"
    make {_npc::2} unflyable
    assert npc {_npc::1} and {_npc::2} are not flyable with "was wrong"
    delete all citizens